### ISSUE TITLE
[Issue]: torch.cuda.mem_get_info function RuntimeError(HIP error: invalid argument)

### ISSUE THREAD

**Issue by jaeyung2** [ROCm/gpu-operator#330]
### Problem Description

I'm try to run sample code in container after install gpu-operator helm chart on my cluster(1.32.8 k8s version). my test code is below. How can I solve this problem? I'd appreciate it if you could let me know.

```python
import torch
if torch.cuda.is_available():
    free_memory_bytes, total_memory_bytes = torch.cuda.mem_get_info()

    free_memory_gb = free_memory_bytes / (1024**3)
    total_memory_gb = total_memory_bytes / (1024**3)

    print(f"Free GPU memory: {free_memory_gb:.2f} GB")
    print(f"Total GPU memory: {total_memory_gb:.2f} GB")

else:
    print("CUDA is not available. Cannot get GPU memory info.")
```

and error message is:
```
Traceback (most recent call last):
  File "/var/lib/jenkins/test.py", line 4, in <module>
    free_memory_bytes, total_memory_bytes = torch.cuda.mem_get_info()
  File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/cuda/memory.py", line 738, in mem_get_info
    return torch.cuda.cudart().cudaMemGetInfo(device)
RuntimeError: HIP error: invalid argument
HIP kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing AMD_SERIALIZE_KERNEL=3
Compile with `TORCH_USE_HIP_DSA` to enable device-side assertions.
```

my pod yaml information:
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: rocm-pytorch-test
  namespace: kube-amd-gpu
  labels:
    app: rocm-pytorch-test
spec:
  restartPolicy: Never
  tolerations:
    - key: "amd.com/gpu"
      operator: "Exists"
      effect: "NoSchedule"
  containers:
    - name: rocm-pytorch
      image: rocm/pytorch:rocm6.4.2_ubuntu22.04_py3.10_pytorch_release_2.6.0
      imagePullPolicy: IfNotPresent
      command: ["sleep", "infinity"]
      resources:
        limits:
          "amd.com/gpu": 8
```

Here is my OS and GPU information
```
OS: NAME="Ubuntu"
VERSION="22.04.5 LTS (Jammy Jellyfish)"
CPU: 
model name	: AMD EPYC 7413 24-Core Processor
GPU:
  Name:                    AMD EPYC 7413 24-Core Processor    
  Marketing Name:          AMD EPYC 7413 24-Core Processor    
  Name:                    AMD EPYC 7413 24-Core Processor    
  Marketing Name:          AMD EPYC 7413 24-Core Processor    
  Name:                    gfx90a                             
  Marketing Name:          AMD Instinct MI250X/MI250          
      Name:                    amdgcn-amd-amdhsa--gfx90a:sramecc+:xnack-
  Name:                    gfx90a                             
  Marketing Name:          AMD Instinct MI250X/MI250          
      Name:                    amdgcn-amd-amdhsa--gfx90a:sramecc+:xnack-
  Name:                    gfx90a                             
  Marketing Name:          AMD Instinct MI250X/MI250          
      Name:                    amdgcn-amd-amdhsa--gfx90a:sramecc+:xnack-
  Name:                    gfx90a                             
  Marketing Name:          AMD Instinct MI250X/MI250          
      Name:                    amdgcn-amd-amdhsa--gfx90a:sramecc+:xnack-
  Name:                    gfx90a                             
  Marketing Name:          AMD Instinct MI250X/MI250          
      Name:                    amdgcn-amd-amdhsa--gfx90a:sramecc+:xnack-
  Name:                    gfx90a                             
  Marketing Name:          AMD Instinct MI250X/MI250          
      Name:                    amdgcn-amd-amdhsa--gfx90a:sramecc+:xnack-
  Name:                    gfx90a                             
  Marketing Name:          AMD Instinct MI250X/MI250          
      Name:                    amdgcn-amd-amdhsa--gfx90a:sramecc+:xnack-
  Name:                    gfx90a                             
  Marketing Name:          AMD Instinct MI250X/MI250          
      Name:                    amdgcn-amd-amdhsa--gfx90a:sramecc+:xnack-
```

### Operating System

Ubuntu 22.04

### CPU

AMD EPYC 7413 24-Core Processor

### GPU

AMD Instinct MI250X/MI250

### ROCm Version

ROCm 6.4.2

### ROCm Component

HIP

**Comment by jaeyung2** [comment]
Hi, @yansun1996  
> 1. Could you please check whether `rocm-smi` or `amd-smi list` could show expected hardware information within the PyTorch image you are using ?

- run `rocm-smi` command
```
root@rocm-pytorch-test:/var/lib/jenkins# rocm-smi


========================================= ROCm System Management Interface =========================================
=================================================== Concise Info ===================================================
Device  Node  IDs              Temp    Power  Partitions          SCLK    MCLK     Fan  Perf  PwrCap  VRAM%  GPU%  
              (DID,     GUID)  (Edge)  (Avg)  (Mem, Compute, ID)                                                   
====================================================================================================================
0       2     0x740c,   31957  40.0°C  87.0W  N/A, N/A, 0         800Mhz  1600Mhz  0%   auto  560.0W  0%     0%    
1       3     0x740c,   7103   36.0°C  0.0W   N/A, N/A, 0         800Mhz  1600Mhz  0%   auto  0.0W    0%     0%    
2       4     0x740c,   9752   40.0°C  90.0W  N/A, N/A, 0         800Mhz  1600Mhz  0%   auto  560.0W  0%     0%    
3       5     0x740c,   52450  35.0°C  0.0W   N/A, N/A, 0         800Mhz  1600Mhz  0%   auto  0.0W    0%     0%    
4       6     0x740c,   49482  44.0°C  93.0W  N/A, N/A, 0         800Mhz  1600Mhz  0%   auto  560.0W  0%     0%    
5       7     0x740c,   60436  40.0°C  0.0W   N/A, N/A, 0         800Mhz  1600Mhz  0%   auto  0.0W    0%     0%    
6       8     0x740c,   35581  42.0°C  85.0W  N/A, N/A, 0         800Mhz  1600Mhz  0%   auto  560.0W  0%     0%    
7       9     0x740c,   20807  39.0°C  0.0W   N/A, N/A, 0         800Mhz  1600Mhz  0%   auto  0.0W    0%     0%    
====================================================================================================================
=============================================== End of ROCm SMI Log ================================================
```

- run `amd-smi list` command
```
root@rocm-pytorch-test:/var/lib/jenkins# amd-smi list
GPU: 0
    BDF: 0000:29:00.0
    UUID: 4fff740c-0000-1000-8072-8ebc89268dca
    KFD_ID: 31957
    NODE_ID: 2
    PARTITION_ID: 0

GPU: 1
    BDF: 0000:2c:00.0
    UUID: 5bff740c-0000-1000-80ed-1333a4145366
    KFD_ID: 7103
    NODE_ID: 3
    PARTITION_ID: 0

GPU: 2
    BDF: 0000:2f:00.0
    UUID: 59ff740c-0000-1000-8012-5243f98885f9
    KFD_ID: 9752
    NODE_ID: 4
    PARTITION_ID: 0

GPU: 3
    BDF: 0000:32:00.0
    UUID: 6bff740c-0000-1000-8061-cce40adb54f7
    KFD_ID: 52450
    NODE_ID: 5
    PARTITION_ID: 0

GPU: 4
    BDF: 0000:ad:00.0
    UUID: 8dff740c-0000-1000-8073-71b5f9c86e6b
    KFD_ID: 49482
    NODE_ID: 6
    PARTITION_ID: 0

GPU: 5
    BDF: 0000:b0:00.0
    UUID: 9cff740c-0000-1000-8070-48f08bcb2ea7
    KFD_ID: 60436
    NODE_ID: 7
    PARTITION_ID: 0

GPU: 6
    BDF: 0000:b3:00.0
    UUID: 0eff740c-0000-1000-80d9-ae2ed94f35e4
    KFD_ID: 35581
    NODE_ID: 8
    PARTITION_ID: 0

GPU: 7
    BDF: 0000:b6:00.0
    UUID: 2eff740c-0000-1000-80af-357d3313eac9
    KFD_ID: 20807
    NODE_ID: 9
    PARTITION_ID: 0
```

> 2. Is the driver pre-installed on the node or installed by GPU operator  ?
It's installed by GPU operator

**Comment by yansun1996** [comment]
ok thanks for the information @jaeyung2 , I think this could be some issues on the PyTorch image since the error message is complaining it cannot find something in the rocm libs, could you please also raise an issue in https://github.com/ROCm/ROCm or https://github.com/ROCm/ROCm-docker ?

**Comment by jaeyung2** [comment]
hi @yansun1996 . Our team just found that the issue occured from ubuntu 22.04. but not in ubuntu 24.04. I tested with hip code like below.

- test.cpp
```cpp
#include <hip/hip_runtime.h>
#include <iostream>

void checkHipError(hipError_t err) {
    if (err != hipSuccess) {
        std::cerr << "HIP Error: " << hipGetErrorString(err) << std::endl;
        exit(EXIT_FAILURE);
    }
}

int main() {
    checkHipError(hipSetDevice(0));
    std::cout << "✅ HIP Runtime and Initialize GPU device success." << std::endl;

    size_t free_bytes, total_bytes;

    hipError_t err = hipMemGetInfo(&free_bytes, &total_bytes);

    if (err != hipSuccess) {
        std::cerr << "❌ Error: Failed to get GPU memory information." << std::endl;
        std::cerr << "HIP Error: " << hipGetErrorString(err) << std::endl;
        return -1;
    }

    std::cout << "🎉 Success: Available to get GPU memory information." << std::endl;

    double free_mb = static_cast<double>(free_bytes) / (1024.0 * 1024.0);
    double total_mb = static_cast<double>(total_bytes) / (1024.0 * 1024.0);
    
    std::cout << "----------------------------------------" << std::endl;
    std::cout << "GPU memory info:" << std::endl;
    std::cout << "  - Total memory (Total): " << total_mb << " MB" << std::endl;
    std::cout << "  - Available memory (Free): " << free_mb << " MB" << std::endl;
    std::cout << "----------------------------------------" << std::endl;

    return 0;
}
```

- ubuntu 22.04 (kernel version: 5.15.0-153-generic, rocm version: 6.4.2)
```
root@rocminfo:/home/rocm-user# ./test 
✅ HIP Runtime and Initialize GPU device success.
❌ Error: Failed to get GPU memory information.
HIP Error: invalid argument
```

- ubuntu 24.04 (kernel version: 6.8.0-83-generic, rocm version: 6.4.2)
```
root@rocminfo:/home/rocm-user# ./test
✅ HIP Runtime and Initialize GPU device success.
🎉 Success: Available to get GPU memory information.
----------------------------------------
GPU memory info:
  - Total memory (Total):65520 MB
  - Available memory (Free): 65446 MB
----------------------------------------
```

**Comment by jaeyung2** [comment]
- In Ubuntu 22.04, the kmm-worker log like below
```
root@mi250-041:~# kubectl logs -f -n kube-amd-gpu kmm-worker-mi250-037-default -c worker
E0918 11:09:31.777162       1 funcs_kmod.go:15] "Could not get the git commit; using <undefined>" err="vcs.revision not found in build info settings" logger="kmm-worker"
I0918 11:09:31.777305       1 funcs_kmod.go:18] "Starting worker" logger="kmm-worker" version="0.0.1" git commit="<undefined>"
I0918 11:09:31.777320       1 funcs_kmod.go:30] "Reading config" logger="kmm-worker" path="/etc/kmm-worker/config.yaml"
I0918 11:09:31.778845       1 worker.go:76] "preparing firmware for loading" logger="kmm-worker" image directory="/tmp/firmwareDir/updates" host mount directory="/var/lib/firmware"
I0918 11:09:32.942374       1 modprobe.go:33] "Running modprobe" logger="kmm-worker" command="/sbin/modprobe -vd /tmp/opt amdgpu"
```
- But in Ubuntu 24.04, the kmm-worker log like below
```
E0918 10:34:02.090162       1 funcs_kmod.go:15] "Could not get the git commit; using <undefined>" err="vcs.revision not found in build info settings" logger="kmm-worker"
I0918 10:34:02.090380       1 funcs_kmod.go:18] "Starting worker" logger="kmm-worker" version="0.0.1" git commit="<undefined>"
I0918 10:34:02.090400       1 funcs_kmod.go:30] "Reading config" logger="kmm-worker" path="/etc/kmm-worker/config.yaml"
I0918 10:34:02.091090       1 worker.go:76] "preparing firmware for loading" logger="kmm-worker" image directory="/tmp/firmwareDir/updates" host mount directory="/var/lib/firmware"
I0918 10:34:02.728754       1 modprobe.go:33] "Running modprobe" logger="kmm-worker" command="/sbin/modprobe -vd /tmp/opt amdgpu"
I0918 10:34:02.739348       1 cmdlog.go:70] "insmod /tmp/opt/lib/modules/6.8.0-79-generic/kernel/drivers/acpi/video.ko.zst " logger="kmm-worker.modprobe.stdout"
I0918 10:34:39.585199       1 cmdlog.go:70] "insmod /tmp/opt/lib/modules/6.8.0-79-generic/kernel/drivers/gpu/drm/display/drm_display_helper.ko.zst " logger="kmm-worker.modprobe.stdout"
I0918 10:34:39.585228       1 cmdlog.go:70] "insmod /tmp/opt/lib/modules/6.8.0-79-generic/kernel/drivers/gpu/drm/drm_suballoc_helper.ko.zst " logger="kmm-worker.modprobe.stdout"
I0918 10:34:39.585263       1 cmdlog.go:70] "insmod /tmp/opt/lib/modules/6.8.0-79-generic/kernel/drivers/gpu/drm/drm_exec.ko.zst " logger="kmm-worker.modprobe.stdout"
I0918 10:34:39.585270       1 cmdlog.go:70] "insmod /tmp/opt/lib/modules/6.8.0-79-generic/updates/dkms/amdkcl.ko " logger="kmm-worker.modprobe.stdout"
I0918 10:34:39.585276       1 cmdlog.go:70] "insmod /tmp/opt/lib/modules/6.8.0-79-generic/updates/dkms/amd-sched.ko " logger="kmm-worker.modprobe.stdout"
I0918 10:34:39.585282       1 cmdlog.go:70] "insmod /tmp/opt/lib/modules/6.8.0-79-generic/updates/dkms/amdxcp.ko " logger="kmm-worker.modprobe.stdout"
I0918 10:34:39.585288       1 cmdlog.go:70] "insmod /tmp/opt/lib/modules/6.8.0-79-generic/updates/dkms/amddrm_buddy.ko " logger="kmm-worker.modprobe.stdout"
I0918 10:34:39.585295       1 cmdlog.go:70] "insmod /tmp/opt/lib/modules/6.8.0-79-generic/updates/dkms/amdttm.ko " logger="kmm-worker.modprobe.stdout"
I0918 10:34:39.585301       1 cmdlog.go:70] "insmod /tmp/opt/lib/modules/6.8.0-79-generic/updates/dkms/amddrm_ttm_helper.ko " logger="kmm-worker.modprobe.stdout"
I0918 10:34:39.585308       1 cmdlog.go:70] "insmod /tmp/opt/lib/modules/6.8.0-79-generic/updates/dkms/amdgpu.ko " logger="kmm-worker.modprobe.stdout"
```

I think somethine went wrong with `/sbin/modprobe -vd /tmp/opt amdgpu` ?

**Comment by jaeyung2** [comment]
> Hi @jaeyung2 I think that's due to the difference of the kernel version. You are comparing the 5.15 vs 6.8 generic kernels, there are always changes happening in the development of the Linux kernel between major versions, so that the kernel module dependency graph could change as well.

Yes, I know. I think Ubuntu 22.04 should also load the 'amdkcl', 'amdxcp' kernel module, but it doesn't work that way. Or do you think only the `amdgpu` kernel module should load in Ubuntu 22.04?

**Comment by yansun1996** [comment]
> > Hi [@jaeyung2](https://github.com/jaeyung2) I think that's due to the difference of the kernel version. You are comparing the 5.15 vs 6.8 generic kernels, there are always changes happening in the development of the Linux kernel between major versions, so that the kernel module dependency graph could change as well.
> 
> Yes, I know. I think Ubuntu 22.04 should also load the 'amdkcl', 'amdxcp' kernel module, but it doesn't work that way. Or do you think only the `amdgpu` kernel module should load in Ubuntu 22.04?

ok, good point @jaeyung2 this line shows it is using inbox driver, looks like blacklist not applied. otherwise it would use amdttm, that's what I remembered before.

Could you please check whether the inbox amdgpu driver was blacklisted or not on that Ubuntu 22.04 ?

```
ttm                    86016  3 drm_vram_helper,amdgpu,drm_ttm_helper
```

**Comment by wonkyooh** [comment]
> > > Hi [@jaeyung2](https://github.com/jaeyung2) I think that's due to the difference of the kernel version. You are comparing the 5.15 vs 6.8 generic kernels, there are always changes happening in the development of the Linux kernel between major versions, so that the kernel module dependency graph could change as well.
> > 
> > 
> > Yes, I know. I think Ubuntu 22.04 should also load the 'amdkcl', 'amdxcp' kernel module, but it doesn't work that way. Or do you think only the `amdgpu` kernel module should load in Ubuntu 22.04?
> 
> ok, good point [@jaeyung2](https://github.com/jaeyung2) this line shows it is using inbox driver, looks like blacklist not applied. otherwise it would use amdttm, that's what I remembered before.
> 
> Could you please check whether the inbox amdgpu driver was blacklisted or not on that Ubuntu 22.04 ?
> 
> ```
> ttm                    86016  3 drm_vram_helper,amdgpu,drm_ttm_helper
> ```

Hi, @yansun1996 Im WonKyo, @jaeyung2 's coworker and I will answer your question.
On ubuntu 22.04 blacklisting amdgpu does not actually blacklist amdgpu module for it is still in the initramfs
```
root@mi250-041:/etc/modprobe.d# cat blacklist.conf 
# This file lists those modules which we don't want to be loaded by
# alias expansion, usually so some other driver will be loaded for the
# device instead.

# evbug is a debug tool that should be loaded explicitly
blacklist evbug

# these drivers are very simple, the HID drivers are usually preferred
blacklist usbmouse
blacklist usbkbd

# replaced by e100
blacklist eepro100

# replaced by tulip
blacklist de4x5

# causes no end of confusion by creating unexpected network interfaces
blacklist eth1394

# snd_intel8x0m can interfere with snd_intel8x0, doesn't seem to support much
# hardware on its own (Ubuntu bug #2011, #6810)
blacklist snd_intel8x0m

# Conflicts with dvb driver (which is better for handling this device)
blacklist snd_aw2

# replaced by p54pci
blacklist prism54

# replaced by b43 and ssb.
blacklist bcm43xx

# most apps now use garmin usb driver directly (Ubuntu: #114565)
blacklist garmin_gps

# replaced by asus-laptop (Ubuntu: #184721)
blacklist asus_acpi

# low-quality, just noise when being used for sound playback, causes
# hangs at desktop session start (Ubuntu: #246969)
blacklist snd_pcsp

# ugly and loud noise, getting on everyone's nerves; this should be done by a
# nice pulseaudio bing (Ubuntu: #77010)
blacklist pcspkr

# EDAC driver for amd76x clashes with the agp driver preventing the aperture
# from being initialised (Ubuntu: #297750). Blacklist so that the driver
# continues to build and is installable for the few cases where its
# really needed.
blacklist amd76x_edac

blacklist amdgpu

root@mi250-041:/etc/modprobe.d# update-initramfs -u
update-initramfs: Generating /boot/initrd.img-5.15.0-153-generic
W: Possible missing firmware /lib/firmware/ast_dp501_fw.bin for module ast
W: Possible missing firmware /lib/firmware/amdgpu/yellow_carp_gpu_info.bin for module amdgpu
W: Possible missing firmware /lib/firmware/amdgpu/vangogh_gpu_info.bin for module amdgpu
W: Possible missing firmware /lib/firmware/amdgpu/cyan_skillfish_rlc.bin for module amdgpu
W: Possible missing firmware /lib/firmware/amdgpu/cyan_skillfish_mec2.bin for module amdgpu
W: Possible missing firmware /lib/firmware/amdgpu/cyan_skillfish_mec.bin for module amdgpu
W: Possible missing firmware /lib/firmware/amdgpu/cyan_skillfish_me.bin for module amdgpu
W: Possible missing firmware /lib/firmware/amdgpu/cyan_skillfish_pfp.bin for module amdgpu
W: Possible missing firmware /lib/firmware/amdgpu/cyan_skillfish_ce.bin for module amdgpu
W: Possible missing firmware /lib/firmware/amdgpu/cyan_skillfish_sdma1.bin for module amdgpu
W: Possible missing firmware /lib/firmware/amdgpu/cyan_skillfish_sdma.bin for module amdgpu
W: Possible missing firmware /lib/firmware/amdgpu/sienna_cichlid_mes.bin for module amdgpu
W: Possible missing firmware /lib/firmware/amdgpu/navi10_mes.bin for module amdgpu
root@mi250-041:/etc/modprobe.d# lsinitramfs /boot/initrd.img-5.15.0-153-generic | grep -i amdgpu.ko
usr/lib/modules/5.15.0-153-generic/kernel/drivers/gpu/drm/amd/amdgpu/amdgpu.ko
```
So, on another node that has amdgpu driver installed via amdgpu-install, i checked the iniramfs to see how the amdgpu module was loaded and it just lists the new amdgpu module that was installed vy amdgpu-install

```
root@mi250-026:~# lsinitramfs /boot/initrd.img-5.15.0-25-generic | grep -i amdgpu.ko
usr/lib/modules/5.15.0-25-generic/updates/dkms/amdgpu.ko
```

Also, I have tested unloading the amdgpu module by running the following command on both ubuntu 24.04 and 22.04 and it seems that only ubuntu 24.04 unloads it and ubuntu 22.04 cannot unload it saying that the module is being used.

```
modprobe -r amdgpu
```

Sorry I do not have the logs of the above command from our severs.

So the next step for us is add the following file to initramfs, then update initramfs, then reboot and as you can see below amdgpu module was not loaded and redeploying the operator again on this server and see if it works.
```
moreh@mi250-041:~$ cat /etc/initramfs-tools/hooks/remove-amdgpu 
#!/bin/sh

PREREQS=""

case $1 in
prereqs)
    echo "${PREREQS}"
    exit 0
    ;;
esac

# Find and delete the amdgpu.ko file from the build directory
find ${DESTDIR} -type f -name "amdgpu.ko" -delete
moreh@mi250-041:~$ lsmod | grep -i amdgpu
```

If you have any other suggestions or solutions please feel free to share with us

**Comment by yansun1996** [comment]
> Okay I am back with the final test and it turns out that on ubunt 22.04.4 adding `blacklist amdgpu` to the `/etc/modprobe.d/blacklist-amdgpu.conf` file does not actually blacklist amdgpu but it requires the users to run `sudo update-initramfs -u` for the changes to be applied. So, after adding the blacklist file then updating the initramfs then rebooting actually blacklisted the amdgpu on the next boot. On the other hand, on ubuntu 24.04.3 just adding the `blacklist amdgpu` to the `/etc/modprobe.d/blacklist-amdgpu.conf` file then rebooting blacklists the amdgpu module. I have yet to check how the `deviceConfig.spec.driver.blacklist: true` value in the values.yaml file work but my guess is that it only add the blacklist file without updating the initramfs.
> 
> ** Below is the command that disables amdgpu in ubuntu 24.04.3**
> ```
> sudo echo 'blacklist amdgpu' >> /etc/modprobe.d/blacklist-amdgpu.conf
> sudo reboot
> ```
> ** Below is the command that disables amdgpu in ubuntu 22.04.4**
> ```
> sudo echo 'blacklist amdgpu' >> /etc/modprobe.d/blacklist-amdgpu.conf
> sudo update-initramfs -u
> sudo reboot
> ```
> 


Hi @wonkyooh thanks for detailed information. so this is an enhancement of the blacklist functionality that we need to do on operator side. We're lacking of the automation to update the intramfs .

Can you confirm after properly blacklisting the inbox driver, is the PyTorch image start to work properly ?

**Comment by wonkyooh** [comment]
> > Okay I am back with the final test and it turns out that on ubunt 22.04.4 adding `blacklist amdgpu` to the `/etc/modprobe.d/blacklist-amdgpu.conf` file does not actually blacklist amdgpu but it requires the users to run `sudo update-initramfs -u` for the changes to be applied. So, after adding the blacklist file then updating the initramfs then rebooting actually blacklisted the amdgpu on the next boot. On the other hand, on ubuntu 24.04.3 just adding the `blacklist amdgpu` to the `/etc/modprobe.d/blacklist-amdgpu.conf` file then rebooting blacklists the amdgpu module. I have yet to check how the `deviceConfig.spec.driver.blacklist: true` value in the values.yaml file work but my guess is that it only add the blacklist file without updating the initramfs.
> > ** Below is the command that disables amdgpu in ubuntu 24.04.3**
> > ```
> > sudo echo 'blacklist amdgpu' >> /etc/modprobe.d/blacklist-amdgpu.conf
> > sudo reboot
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ** Below is the command that disables amdgpu in ubuntu 22.04.4**
> > ```
> > sudo echo 'blacklist amdgpu' >> /etc/modprobe.d/blacklist-amdgpu.conf
> > sudo update-initramfs -u
> > sudo reboot
> > ```
> 
> Hi [@wonkyooh](https://github.com/wonkyooh) thanks for detailed information. so this is an enhancement of the blacklist functionality that we need to do on operator side. We're lacking of the automation to update the intramfs .
> 
> Can you confirm after properly blacklisting the inbox driver, is the PyTorch image start to work properly ?

Hi @yansun1996,
After leaving the comment above I did some more tests.
1. I reinstalled the OS on the test server and after installing OS i blacklisted the amdgpu then run the update-initrmafs then deployed kubernetes on it and deployed the gpu operator on it then ran a deepseek model using vllm and it worked fine.
2. I reintalled the OS on the same server with pxe and in the autoinstall's late command i added the blacklist and the initramfs and then deploying kubernetes and gpu-operator on it. Then, I ran the Deepseek using vllm on it and it also worked fine as well.

**Comment by yansun1996** [comment]
> > > Okay I am back with the final test and it turns out that on ubunt 22.04.4 adding `blacklist amdgpu` to the `/etc/modprobe.d/blacklist-amdgpu.conf` file does not actually blacklist amdgpu but it requires the users to run `sudo update-initramfs -u` for the changes to be applied. So, after adding the blacklist file then updating the initramfs then rebooting actually blacklisted the amdgpu on the next boot. On the other hand, on ubuntu 24.04.3 just adding the `blacklist amdgpu` to the `/etc/modprobe.d/blacklist-amdgpu.conf` file then rebooting blacklists the amdgpu module. I have yet to check how the `deviceConfig.spec.driver.blacklist: true` value in the values.yaml file work but my guess is that it only add the blacklist file without updating the initramfs.
> > > ** Below is the command that disables amdgpu in ubuntu 24.04.3**
> > > ```
> > > sudo echo 'blacklist amdgpu' >> /etc/modprobe.d/blacklist-amdgpu.conf
> > > sudo reboot
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > ** Below is the command that disables amdgpu in ubuntu 22.04.4**
> > > ```
> > > sudo echo 'blacklist amdgpu' >> /etc/modprobe.d/blacklist-amdgpu.conf
> > > sudo update-initramfs -u
> > > sudo reboot
> > > ```
> > 
> > Hi [@wonkyooh](https://github.com/wonkyooh) thanks for detailed information. so this is an enhancement of the blacklist functionality that we need to do on operator side. We're lacking of the automation to update the intramfs .
> > 
> > Can you confirm after properly blacklisting the inbox driver, is the PyTorch image start to work properly ?
> 
> Hi @yansun1996,
> After leaving the comment above I did some more tests.
> 1. I reinstalled the OS on the test server and after installing OS i blacklisted the amdgpu then run the update-initrmafs then deployed kubernetes on it and deployed the gpu operator on it then ran a deepseek model using vllm and it worked fine.
> 2. I reintalled the OS on the same server with pxe and in the autoinstall's late command i added the blacklist and the initramfs and then deploying kubernetes and gpu-operator on it. Then, I ran the Deepseek using vllm on it and it also worked fine as well.
> 

Thanks for the confirmation  @wonkyooh we will enhance the blacklist function on operator side
